src/global/entities/orders.entity.ts
src/orders/orders.service.spec.ts

코드에 대한 자세한 설명을 쓰는곳입니다.
👻 이모지도 넣겠습니다.
좋습미니다.

풀리퀘 연습중입니다. #6

---

package-lock.json
package.json
src/app.module.ts
src/config/orm.config.ts
src/global/entities/categories.entity.ts
src/global/entities/likes.entity.ts
src/global/entities/notices.entity.ts
src/global/entities/orders.entity.ts
src/global/entities/products.entity.ts
src/global/entities/users.entity.ts
src/orders/dto/create-order.dto.ts
src/orders/dto/update-order.dto.ts
src/orders/orders.controller.spec.ts
src/orders/orders.controller.ts
src/orders/orders.module.ts
src/orders/orders.service.spec.ts
src/orders/orders.service.ts

- 다음부턴 자주 풀리퀘하여 기록을 남기겠습니다.
- 테스트 코드는 미작성 입니다.
- API 토대로 작업하였습니다. [API 주소](https://boatneck-hardcover-0f0.notion.site/API-c55867c78bff4ba19ee32f2a1afe9832)
- 다음 일정 :  3월 6일 ~~ // 테스트코드 작성, 로그인 정보에서 유저정보 가져오기, 프론트 작업 시작
> #### ✅ TODO
- ✅내가 파는 상품 목록 보기 - `@Get('mySellProduct/:sellerId')`
- 판매자 => 판매 등록한 상품 목록 보기
- ✅제시된 가격 목록 보기 -  `@Get('products/:productId')` 
- 판매자 => 등록한 특정 물건에 대한 제시된 가격 목록 보기
- ✅내가 가격 제시한 상품 목록 보기 - `@Get('mySellProduct/:sellerId')`
- 구매자 => 특정 물건에 대해 제시한 가격 확인
- ✅성사된 거래 판매자 정보 보기 - `@Get('buyResult/:userId/:orderId')`
- 구매자 => 가격제시  요청을 수락한 상품에 판매자 정보 확인
- ✅성사된 거래 구매자 정보 보기 `@Get('sellResult/:userId/:orderId')`
- 판매자 => 가격제시  요청하고 구매자 정보 확인 
- ✅구매 목록 - `@Get('myBuyList/:userId')`
- 사용자 => 자신이 구매한 상품 목록
- ✅판매 목록 - ` @Get('mySellList/:userId')`
- 사용자 => 자신이 판매한 상품 목록
- …

Order 기능구현

---

src/orders/orders.controller.ts
src/orders/orders.service.ts
src/views/index.ejs
src/views/order-findMyProductsDealCheck.ejs

Param 정보를 아직 구현못했습니다.
간단한 상품리스트 페이지를 만들어서 테스트 하겠습니다.

ADD: Order/임시프론트 <제시된 가격목록 보기>

---

src/orders/orders.controller.ts
src/orders/orders.service.ts
src/views/index.ejs
src/views/order-myBuyList.ejs
src/views/order-sellResult.ejs

내가 구매한 목록 임시 프론트 제작
> order/front/myBuyList
> #### ✅ TODO
> 프론트에서 데이터 적용하기

ADD: Order/임시프론트 <내가 구매한 목록>

---

src/orders/orders.controller.ts
src/orders/orders.service.ts
src/views/index.ejs
src/views/order-findMyPick.ejs

ADD: Order/임시프론트 <내가 가격제시한 상품 목록보기>

---

src/orders/orders.controller.ts
src/orders/orders.service.ts
src/views/index.ejs
src/views/order-buyResult.ejs

ADD: Order/임시프론트 <성사된 거래 판매자 정보보기>

---

src/orders/orders.controller.ts
src/orders/orders.service.ts
src/views/index.ejs
src/views/order-mySellList.ejs

ADD: Order/임시프론트 <내가 판매한 목록>

---

src/orders/orders.controller.ts
src/orders/orders.service.ts
src/views/order-layout.ejs
src/views/view.controller.ts

order-layout 페이지
GET요청 업데이트 하였습니다.

ADD: Order/FRONT <order-layout GET요청>

---

src/views/admin/admin-productById.ejs
src/views/admin/admin-products.ejs

ADD: 관리자 상품 페이지 레이아웃 #8

---

src/views/admin/admin-category.ejs
src/views/admin/admin-header.ejs
src/views/admin/admin-notices.ejs
src/views/admin/admin-products.ejs
src/views/admin/admin-users.ejs

✅ ADD: 관리자 페이지 헤더와 버튼들 기본 레이아웃
#8

ADD: 관리자 프론트 헤더 layout

---

src/admin/admin.controller.ts
src/views/admin/admin-category.ejs
src/views/admin/admin-categoryPost.ejs
src/views/admin/admin-footer.ejs
src/views/admin/admin-header.ejs
src/views/admin/admin-noticeById.ejs
src/views/admin/admin-noticePost.ejs
src/views/admin/admin-notices.ejs
src/views/admin/admin-productById.ejs
src/views/admin/admin-userById.ejs
src/views/admin/admin-users.ejs

관리자 페이지 카테고리/공지 목록,상세보기 레이아웃 추가하였습니다. 
footer의 버튼을 추가하였습니다.

ADD: 관리자 카테고리/공지/footer 레이아웃 추가

---

src/app.controller.ts
src/orders/orders.service.ts
src/views/js/order-layout.js
src/views/login.ejs
src/views/order-layout.ejs
src/views/test-product.ejs

Order/FRONT <가격 제시 목록, 가격 제시 수락>

ADD: Order/FRONT <가격 제시 목록, 가격 제시 수락>

---

src/app.module.ts
src/products/products.service.ts

Merge: feature/prodcut -> dev
로그인 + 상품 + 오더 + 어드민

Merge: feature/prodcut -> dev

---

src/admin/admin.controller.ts
src/orders/orders.controller.ts
src/views/admin/admin-category.ejs
src/views/admin/admin-header.ejs
src/views/admin/admin-login.controller.ts
src/views/admin/admin-products.ejs
src/views/admin/admin-users.ejs
src/views/js/order-layout.js

orders controller / order-layout.js API 를 좀 더 Restful 하게 바꾸었습니다. 
ex) mySellList --> me/sell/list
-----------
admin category 수정 프론트 페이지 수정하였습니다.
#8

Change: orders controller/order-layout.js API 바꿈

---

src/admin/admin.controller.ts
src/admin/admin.service.ts
src/views/admin/admin-products.ejs
src/views/admin/js/admin-layout.js

관리자 상품 10개씩 가져오기(백엔드)로 페이지네이션.
스크롤이 아닌 버튼으로 더 불러옴.
#8

Feat: pagination for admin products

---

src/admin/admin.controller.ts
src/views/admin/admin-products.ejs
src/views/admin/js/admin-layout.js

Feat: Admin/pagination/scroll

---

src/global/entities/likes.entity.ts
src/global/entities/productimages.entity.ts
src/global/entities/products.entity.ts
src/global/entities/users.entity.ts
src/products/products.controller.ts
src/products/products.module.ts
src/products/products.service.ts
src/views/js/product-main.js
src/views/product/products-detail.ejs

조회수
찜하기(기능완성)
> 
> #### ✅ TODO
> 프론트에서 자신의 찜 유무에 따라 '찜하기',취소하기'로 나눠서 보여줘야댐

ADD: Order <조회수,찜하기>

---

src/admin/admin.controller.ts
src/app.controller.ts
src/auth/strategy/jwt-google.strategy.ts
src/global/filter/http-exception-filter.ts
src/main.ts
src/orders/orders.controller.ts
src/social/social.controller.ts
src/social/social.service.ts
src/user/dto/create-user.dto.ts
src/user/user.controller.ts
src/user/user.service.ts
src/views/js/get-edit-user-information.js
src/views/js/get-user-information.js
src/views/js/google-user-edit.js
src/views/js/login-and-signin.js
src/views/js/logout.js
src/views/js/order-layout.js
src/views/js/signup.js
src/views/js/user-edit.js
src/views/mypage-edit-google.ejs
src/views/mypage-edit.ejs
src/views/mypage.ejs

#105 
> feature/mypage
> #### ✅ TODO
> 마이페이지 
#105

Merge: Feature/mypage -> dev 

---

src/admin/admin.controller.ts
src/admin/admin.module.ts
src/admin/admin.service.ts
src/auth/auth.controller.ts
src/auth/auth.service.ts
src/email/email.service.ts
src/global/entities/users.entity.ts
src/views/admin/admin-userById.ejs
src/views/admin/js/admin-header.js
src/views/admin/js/admin-layout.js
src/views/js/login-and-signin.js

-신고 확인 시 경고 누적 
-경고 누적 5회 이상 시 자동 밴처리/ 해당 유저에게 이메일 전송/ 리프레시 토큰 레디스에서 삭제
-벤처리 유저 로그인 불가
-관리자 상품 api 변경 (/products -> /admin/products
#127

Merge Feature/warning ->dev

---

src/admin/admin.service.ts
src/orders/orders.controller.ts
src/orders/orders.service.ts
src/products/products.service.ts
src/views/js/order-layout.js
src/views/js/product-main.js

order.service.ts 리팩토링 (getBuyList,getSellList)
기능 추가 상품검색에 페이지네이션
프론트 수정 판매내역,구매목록에 판매자,구매자 정보가 모달로 나오게
> featur/order
> #### ✅ TODO
> 

Merge: Feature/order -> dev

---

src/products/products.controller.ts
src/products/products.service.ts
src/views/product/products-detail.ejs
src/views/product/products-upload.ejs

상품delete 복구, 에러처리 오류 해결
업로드 리펙토리, 프론트 미세수정
> Feature/product
> #### ✅ TODO
> 
#43

Merge: Feature/product -. dev

---

src/email/email.service.ts
src/products/dto/create-product.dto.ts
src/views/js/signup.js
src/views/signup.ejs

#38 
> feature/emailverify
> #### ✅ TODO
> 이메일 인증 프론트단 구현
#38 
그외 수정사항으로 product.dto의 예외처리 (추후 validate pipe를 통한 예외처리 부탁드립니다.)

ADD: 이메일 인증 프론트단 구현 #38

---

src/app.controller.ts
src/orders/orders.service.ts
src/products/products.service.ts
src/public/css/style.css
src/public/js/order/order-buyList.js
src/public/js/order/order-dealAccept.js
src/public/js/product/product-detail.js
src/views/login.ejs
src/views/main-header.ejs
src/views/order/order-buyList.ejs
src/views/order/order-dealAccept.ejs
src/views/order/order-sellList.ejs
src/views/signup.ejs

로그인 -> 회원가입
랜더경로 수정
> 
> #### ✅ TODO
> 

Merge: feature/front -> dev

---

src/admin/admin.service.spec.ts
src/app.controller.ts
src/products/products.controller.ts
src/products/products.service.ts
src/public/js/header.js
src/public/js/like/like.js
src/public/js/notice/notice.js
src/public/js/product/product-create.js
src/public/js/product/product-list.js
src/public/js/report/report-create.js
src/views/main-header.ejs
src/views/product/product-create.ejs
src/views/product/products-detail.ejs
src/views/report-create.ejs

-관심,신고,공지,상품목록 localhost 지움 
-메인 페이지네이션 수정
-상품 등록 추가

Merge Fix/front -> dev

---

src/views/js/signup.js

#152 
> feature/login
> #### ✅ TODO
> 프론트 수정
#152

ADD: Email Verify

---

src/global/entities/orders.entity.ts
src/main.ts
src/orders/orders.controller.ts
src/orders/orders.service.ts

Merge: Swagger Order -> feature/Swagger

---

src/global/entities/products.entity.ts
src/products/dto/create-product.dto.ts
src/products/products.controller.ts

products스웨거 추가, createProductsdto에 이미지 항목추가
> Feature/product swagger
> #### ✅ TODO
> 예시 넣기

Merge: Feature/product swagger->Feature/swagger

---

.gitignore
Dockerfile

#170 
> test/CICD
> #### ✅ TODO
> Dockerfile수정하여 서버 로컬에서 돌리기
#170

Merge: Test/cicd -> dev

---

src/admin/admin.controller.ts
src/email/email.module.ts
src/global/entities/categories.entity.ts
src/global/entities/products.entity.ts
src/global/entities/reports.entity.ts
src/views/js/withdrawal-service.js

유저 삭제 수정
> user delete
> #### ✅ TODO
> 엔티티 cascade 설정, axios에 api빠진거

Merge : Refactor: user delete fix -> dev

---

src/social/social.controller.ts
src/views/admin/admin-products.ejs
src/views/admin/js/admin-layout.js
src/views/js/signup.js

> dev 
> #### ✅ TODO
> 자잘한 버그수정 (구글 로그인 안되는 버그 등..)
dev

merge: Dev -> Main
